version: '2.2'
services:
  eureka-servicen:
    image: eurekaservicedockerimagenew
    expose:
      - 8083
    ports:
      - 8083:4202
    networks:
      - outside
  coin-servicen:
    image: coinservicedockerimagenew
    expose:
      - 8082
    ports:
      - 8082:4203
    networks:
      - outside
    depends_on:
      - eureka-servicen
networks:
  outside:
    external:
      name: testnetwork